### PR TITLE
Fixes #12 - multiple signing keys in metadata

### LINKED ISSUE #12: Metadata containing multiple "signing" keys not parsed properly
Net::SAML2::IdP assumes only new signing certificate in metadata.xml.  Multiple signing certificates will cause the verification to fail and the IdP object creation to fail

### PR DESCRIPTION
**Pull request by timlegge**
Undecided if this is the best approach.  Need to do more testing against an actual IdP as well as look at the impact if any on the user/developer and docs.

### CODE REVIEW

**Review by timlegge — COMMENTED** [review]
review of test files

File: lib/Net/SAML2/IdP.pm [hunk 1]
```diff
@@ -182,14 +209,25 @@ sub BUILD {
...
+                ## BUGBUG this is failing for valid things ...
+                eval { $ca->verify($cert) };
+                if (!$@) {
+                    $verified = 1;
+                } else {
+                    $error = $@;
+                }
             }
         }
+        #TODO: This needs to be fixed for multiple error - multiple certs
```
[the remark this answers is not in the document]
Comment (timlegge) [reply lib/Net/SAML2/IdP.pm:215]: Need to look at this again - have forgotten why I used BUILDARGS

**Comment by timlegge** [comment]
rebase against 0.52

**Comment by timlegge** [comment]
@waterkip If you ever have time to take a look I would appreciate another set of eyes.

File: lib/Net/SAML2/Binding/Redirect.pm [hunk 2]
```diff
@@ -214,22 +233,27 @@ sub verify {
...
+            } elsif ($sigalg eq 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha224') {
+                $rsa_pub->use_sha224_hash;
+            } elsif ($sigalg eq 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha384') {
+                $rsa_pub->use_sha384_hash;
+            } elsif ($sigalg eq 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha512') {
+                $rsa_pub->use_sha512_hash;
+            } elsif ($sigalg eq 'http://www.w3.org/2000/09/xmldsig#rsa-sha1') {
+                $rsa_pub->use_sha1_hash;
+            } else {
+                die "Unsupported Signature Algorithim: $sigalg";
```
Comment (waterkip) [inline lib/Net/SAML2/Binding/Redirect.pm:252]: As we are looping over certs, I'm not sure if we should die when we don't support things. Perhaps we do support others. I think a warn is a better option. Or perhaps let the caller decide if they want to die here.

File: lib/Net/SAML2/Binding/Redirect.pm [hunk 3]
```diff
@@ -214,22 +233,27 @@ sub verify {
...
+            }
+            die "bad sig" unless $rsa_pub->verify($signed, $sig);
```
Comment (waterkip) [inline lib/Net/SAML2/Binding/Redirect.pm:254]: Similar as above.

File: lib/Net/SAML2/IdP.pm [hunk 4]
```diff
@@ -223,22 +227,42 @@ Called after the object is created to validate the IdP using the cacert
...
+        my $verified = 0;
+        my $error = "";
+        my @certs;
+
+        for my $pem (@{ $params{certs} }) {
+            for my $use (keys %{$pem}) {
+                my $cert = Crypt::OpenSSL::X509->new_from_string($pem->{$use});
+                ## BUGBUG this is failing for valid things ...
+                eval { $ca->verify($cert) };
+                if (!$@) {
```
Comment (waterkip) [inline lib/Net/SAML2/IdP.pm:248]:
```
if ($@) { do the error condition; next }
# continue with the good stuff.
```
I think that we should work only with the good certs, ignore the incorrect ones and if that means that the XML cannot be validated for the incorrect certs, that will be noticed soon enough.

Now, if we have no correct certs: we should die, although I may opt for croaking. We don't do anything wrong, we are getting incorrect data from the caller.

File: lib/Net/SAML2/IdP.pm [hunk 5]
```diff
@@ -278,13 +302,28 @@ sub art_url {
...
+be multiple verified certs in $self->certs.  At this point any certs in the IdP
+have been verified and are valid for the specified use.  All certs are of type
+$use are returned.
 
 =cut
 
 sub cert {
     my($self, $use) = @_;
-    return $self->certs->{$use};
+    my @certs;
```
Comment (waterkip) [inline lib/Net/SAML2/IdP.pm:317]: Idea: perhaps have two attributes: cert_sign, cert_encrypt and just return either.

File: t/13-metadata-multiple-signing.t [hunk 6]
```diff
@@ -0,0 +1,43 @@
+use Test::Lib;
+use Test::Net::SAML2;
+use Net::SAML2::IdP;
+
+my $xml = path('t/idp-metadata-multiple-signing.xml')->slurp;
```
Comment (waterkip) [inline t/13-metadata-multiple-signing.t:5]: I'm a bit of a fan to put testing data in a t/data dir, so everything is at one place.

File: lib/Net/SAML2/IdP.pm [hunk 7]
```diff
@@ -172,12 +172,14 @@ sub new_from_xml {
...
-    {
-        my $use = $key->getAttribute('use') || 'signing';
+    my @certs = ();
+    my $key_nodeset =
+        $xpath->findnodes('//md:EntityDescriptor/md:IDPSSODescriptor/md:KeyDescriptor');
 
+    while (my $key = $key_nodeset->shift())
+    {
         $key->setNamespace('http://www.w3.org/2000/09/xmldsig#', 'ds');
+        my $use = $key->getAttribute('use') || 'signing';
```
Comment (waterkip) [inline lib/Net/SAML2/IdP.pm:182]: I would say:

* If there is only 1 cert without a 'use' attribute we flag it as both a signing and encryption cert.
* If there isn't a 'use' attribute with more than 1 key we die because we don't know the intention of the other party.

File: lib/Net/SAML2/IdP.pm [hunk 8]
```diff
@@ -223,22 +227,42 @@ Called after the object is created to validate the IdP using the cacert
...
+    my $orig = shift;
+    my $self = shift;
+
+    my %params = @_;
+
+    if ($params{cacert}) {
+        my $ca = Crypt::OpenSSL::Verify->new($params{cacert}, { strict_certs => 0, });
+
+        my $verified = 0;
+        my $error = "";
```
Comment (waterkip) [inline lib/Net/SAML2/IdP.pm:240]: I feel like $error should be an array in this context. Each cert can have a different error. At line 252 we just replace the error with the latest and greatest error we get.

File: lib/Net/SAML2/Binding/Redirect.pm [hunk 9]
```diff
@@ -97,7 +97,7 @@ The double encoding requires it to be decoded prior to processing.
 
 =cut
 
-has 'cert' => (isa => 'Str', is => 'ro', required => 1);
+has 'cert' => (isa => 'ArrayRef', is => 'ro', required => 1);
```
Comment (waterkip) [inline lib/Net/SAML2/Binding/Redirect.pm:100]: `ArrayRef[Str]` would be good here I think

File: lib/Net/SAML2/IdP.pm [hunk 10]
```diff
@@ -66,7 +66,7 @@ has 'cacert'   => (isa => 'Maybe[Str]',   is => 'ro', required => 1);
 has 'sso_urls' => (isa => 'HashRef[Str]', is => 'ro', required => 1);
 has 'slo_urls' => (isa => 'Maybe[HashRef[Str]]', is => 'ro');
 has 'art_urls' => (isa => 'Maybe[HashRef[Str]]', is => 'ro');
-has 'certs'    => (isa => 'HashRef[Str]',        is => 'ro', required => 1);
+has 'certs'    => (isa => 'ArrayRef[HashRef[Str]]', is => 'ro', required => 1);
```
Comment (waterkip) [inline lib/Net/SAML2/IdP.pm:69]: Isn't this an `hashref[arrayref[str]]`? multiple signing keys, have `@{$certs->{signing}}`

File: lib/Net/SAML2/IdP.pm [hunk 11]
```diff
@@ -185,6 +185,8 @@ sub new_from_xml {
     {
         my $use = $key->getAttribute('use') || 'signing';
 
+        my @certs = ();
```
Comment (waterkip) [inline lib/Net/SAML2/IdP.pm:188]: I would make this a hashref with $use for the keys and than an array, that makes the logic easier I think. It means `$self->certs->{signing}` will really easy to accomplish.

File: lib/Net/SAML2/IdP.pm [hunk 12]
```diff
@@ -290,13 +314,28 @@ sub art_url {
...
+to be contained in the metadata and therefore possible for them to be there to
+be multiple verified certs in $self->certs.  At this point any certs in the IdP
+have been verified and are valid for the specified use.  All certs are of type
+$use are returned.
 
 =cut
 
 sub cert {
     my($self, $use) = @_;
-    return $self->certs->{$use};
```
Comment (waterkip) [inline lib/Net/SAML2/IdP.pm:299]: If we would use the hashref here it would automatically return the array ref. Removing all the logic you added below.

File: lib/Net/SAML2/Binding/Redirect.pm [hunk 13]
```diff
@@ -264,26 +264,26 @@ sub verify {
...
+            $rsa_pub->use_sha384_hash;
+        } elsif ($sigalg eq 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha512') {
+            $rsa_pub->use_sha512_hash;
+        } elsif ($sigalg eq 'http://www.w3.org/2000/09/xmldsig#rsa-sha1') {
+            $rsa_pub->use_sha1_hash;
+        } else {
+            $errors{$cert->fingerprint_sha256} = "Unsupported Signature Algorithim: $sigalg";
+            warn "Unsupported Signature Algorithim: $sigalg";
+        }
+        if (!$rsa_pub->verify($signed, $sig)) {
```
Comment (waterkip) [inline lib/Net/SAML2/Binding/Redirect.pm:284]: This is ok with multiple signing keys. It supports key rollover. You advertise two keys. Sign it with the old one. Then flip the key sign it with the new one and your rollover is complete after which the old key is removed. If you die, this defauts the purpose. As soon as we've verified we should return an ok and we are done.

File: lib/Net/SAML2/Binding/Redirect.pm [hunk 14]
```diff
@@ -262,6 +262,7 @@ sub verify {
 
     $sig = decode_base64($sig);
 
+    my $verified = 0;
     my %errors;
     foreach my $crt (@{$self->cert}) {
```
Comment (waterkip) [inline lib/Net/SAML2/Binding/Redirect.pm:267]: This should move to `_verify($signed)` or something similar.
We can than do:
```
if (!$self->_verified) {
    croak/confess/die "Could not verify XML due to invalid signature(s)";
}
# Do things because it was verified
```

Comment (waterkip) [reply lib/Net/SAML2/Binding/Redirect.pm:273]: `sub _verified($signed)` to be more precise :)

File: lib/Net/SAML2/IdP.pm [hunk 15]
```diff
@@ -290,7 +320,13 @@ sub art_url {
 
 =head2 cert( $use )
 
-Returns the IdP's certificate for the given use (e.g. C<signing>).
+Returns the IdP's certificates for the given use (e.g. C<signing>).
```
Comment (waterkip) [inline lib/Net/SAML2/IdP.pm:323]: Just as a note: We need to specify this as a breaking change for the release.

**Review by waterkip — APPROVED** [review]
lgtm 👍🏼
